# Generated by Django 5.1.7 on 2025-03-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ppdfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagcenter',
            name='dmail',
        ),
    ]
