# Generated by Django 5.1.7 on 2025-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_diagcenter_dmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagcenter',
            name='dmail',
            field=models.CharField(default='hospital@gmail.com', max_length=200),
        ),
    ]
